const NAMESPACE = 'LOGIN';
export const PERFORM_LOGIN = `${NAMESPACE}/PERFORM_LOGIN`;
export const PERFORM_LOGIN_SUCCESS = `${NAMESPACE}/PERFORM_LOGIN_SUCCESS`;
export const PERFORM_LOGIN_FAILED = `${NAMESPACE}/PERFORM_LOGIN_FAILED`;
export const CLEAR_PERFORM_LOGIN = `${NAMESPACE}/CLEAR_PERFORM_LOGIN`;